variable "domain_name" {}
variable "azs" {}
variable "public_subnets" {}
variable "cidr" {}
variable "availability_zones" {}
variable "ssl_cert_arn" {}
variable "vpc_id" {}
variable "subnet_ids" {}
variable "ecr_nginx_uri" {}
variable "ecr_app_uri" {}
variable "tags" {}
