version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${account_id}.dkr.ecr.${region}.amazonaws.com
      - REPOSITORY_URI=${repository_url}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the application Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - echo ------------------
      - echo Building the Nginx Docker image...
      - docker build -t 032796414879.dkr.ecr.us-east-1.amazonaws.com/scubadivedubai-api-nginx:latest ./nginx/ 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push 032796414879.dkr.ecr.us-east-1.amazonaws.com/scubadivedubai-api-nginx:latest
      - echo Writing image definitions file...
      - printf '[{"name":"${container_name}","imageUri":"%s"},{"name":"nginx","imageUri":"032796414879.dkr.ecr.us-east-1.amazonaws.com/scubadivedubai-api-nginx:latest"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes

  # aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 032796414879.dkr.ecr.us-east-1.amazonaws.com